import logging
import json
from typing import Dict, Any
from langchain_core.messages import HumanMessage
from app.config import settings, has_llm_credentials, get_llm

logger = logging.getLogger("startup_advisor.agents.report_generator")

def run_report_generator(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Report Generator Agent: Integrates all agent outputs into a beautiful,
    executive-ready Markdown validation report.
    """
    idea = state["idea"]
    logger.info(f"Running Report Generator Agent for idea: '{idea[:50]}'")
    
    logs = list(state.get("logs") or [])
    logs.append("Report Generator Agent: Formatting aggregate data into Markdown layout...")
    
    # Extract states
    plan = state.get("plan") or ""
    competitors = state.get("competitors") or []
    market_analysis = state.get("market_analysis") or {}
    risks = state.get("risks") or {}
    tech_stack = state.get("tech_stack") or {}
    
    if not has_llm_credentials():
        # Fallback markdown compile
        mock_report = f"""# Startup Idea Validation Report: {idea}

## 📊 Executive Dashboard
* **Target Audience**: {market_analysis.get('target_audience', 'Not specified')}
* **Monetization**: {market_analysis.get('monetization', 'Not specified')}
* **Overall recommendation**: **GO** (With low-cost mobile MVP validation)

---

## 📋 Custom Research Plan
{plan}

---

## 🔍 Competitive Landscape
The following table summarizes direct and indirect competitors in this niche:

| Competitor | URL | Focus | Strengths | Weaknesses |
| :--- | :--- | :--- | :--- | :--- |
"""
        for comp in competitors:
            mock_report += f"| **{comp.get('name')}** | [{comp.get('url')}]({comp.get('url')}) | {comp.get('description')} | {comp.get('strengths')} | {comp.get('weaknesses')} |\n"
            
        mock_report += f"""
---

## 📈 Market Sizing (TAM/SAM/SOM)
* **Total Addressable Market (TAM)**: {market_analysis.get('tam', 'Not estimated')}
* **Serviceable Addressable Market (SAM)**: {market_analysis.get('sam', 'Not estimated')}
* **Serviceable Obtainable Market (SOM)**: {market_analysis.get('som', 'Not estimated')}

### Calculation Logic:
{market_analysis.get('sizing_breakdown', 'No logic supplied.')}

---

## ⚡ SWOT and Risk Mitigations

### SWOT Matrix
* **Strengths**: {', '.join(risks.get('swot', {}).get('strengths', []))}
* **Weaknesses**: {', '.join(risks.get('swot', {}).get('weaknesses', []))}
* **Opportunities**: {', '.join(risks.get('swot', {}).get('opportunities', []))}
* **Threats**: {', '.join(risks.get('swot', {}).get('threats', []))}

### Critical Risk Factors:
| Risk Category | Description | Probability | Impact | Mitigation |
| :--- | :--- | :---: | :---: | :--- |
"""
        for risk in risks.get("matrix", []):
            mock_report += f"| {risk.get('risk_category')} | {risk.get('description')} | {risk.get('probability')} | {risk.get('impact')} | {risk.get('mitigation')} |\n"
            
        mock_report += f"""
---

## 🛠️ Technical Implementation Blueprint
* **Frontend Framework**: {tech_stack.get('frontend', 'Not specified')}
* **Backend middleware**: {tech_stack.get('backend', 'Not specified')}
* **Core Database**: {tech_stack.get('database', 'Not specified')}
* **Hosting Platforms**: {tech_stack.get('infrastructure_hosting', 'Not specified')}
* **Monthly infrastructure budget**: {tech_stack.get('cost_estimate', 'Not specified')}

### Recommended MVP Features (Must-Have):
"""
        for feature in tech_stack.get("mvp_features", []):
            mock_report += f"- {feature}\n"
            
        mock_report += f"\n*CTO Justification*: {tech_stack.get('justification', 'No technical notes.')}\n"
        
        return {
            "report": mock_report,
            "current_agent": "report_generator",
            "logs": logs + ["Report Generator Agent: Completed report layout compilation (Mock Fallback)."]
        }
        
    try:
        llm = get_llm(temperature=0.2)
        
        # Format package for formatting instructions
        state_data_summary = {
            "idea": idea,
            "plan": plan,
            "competitors": competitors,
            "market_analysis": market_analysis,
            "risks": risks,
            "tech_stack": tech_stack
        }
        
        prompt = f"""
You are the Lead Editor and Principal Business Architect (Report Generator Agent).
Your task is to take the structured JSON datasets generated by the validation agents and compile them into a beautiful, detailed, publication-quality Startup Idea Validation Report.

Here is the structured input data:
{json.dumps(state_data_summary, indent=2)}

Format the report using clean Markdown. Include the following sections:
1. Executive Dashboard (Clean visual bullet points, Go/No-Go verdict, target audience, pricing).
2. Analysis Strategy (From the plan).
3. Competitive Landscape (Render a markdown table listing Name, URL, Description, Strengths, and Weaknesses for each competitor).
4. Market sizing (TAM, SAM, SOM, and a detailed paragraph explaining the bottom-up calculation logic).
5. SWOT Analysis (Two-column layout or list, and a markdown table displaying the Risk Matrix with columns: Risk Category, Description, Probability, Impact, Mitigation).
6. Technical Blueprint & Infrastructure Budget (Lists for Frontend, Backend, Database, Hosting, MVP Features, and Cost Estimate, plus the technical justification).
7. Final Recommendations (Strategic next steps for customer discovery).

Use bolding, clean separation, and markdown tables to make the report look highly professional.
Do not include any wrapper strings. Begin directly with the H1 header.
"""
        response = llm.invoke([HumanMessage(content=prompt)])
        report_content = response.content.strip()
        
        return {
            "report": report_content,
            "current_agent": "report_generator",
            "logs": logs + ["Report Generator Agent: Generated finalized validation report in Markdown."]
        }
    except Exception as e:
        logger.error(f"Error in Report Generator Agent: {e}. Compiling report locally.")
        
        # Build local markdown from state
        local_report = f"""# Startup Idea Validation Report: {idea}

## 📊 Executive Dashboard
* **Target Audience**: {market_analysis.get('target_audience', 'Not specified')}
* **Monetization**: {market_analysis.get('monetization', 'Not specified')}
* **Overall recommendation**: **GO** (With low-cost mobile MVP validation)

---

## 📋 Custom Research Plan
{plan}

---

## 🔍 Competitive Landscape
The following table summarizes direct and indirect competitors in this niche:

| Competitor | URL | Focus | Strengths | Weaknesses |
| :--- | :--- | :--- | :--- | :--- |
"""
        for comp in competitors:
            local_report += f"| **{comp.get('name')}** | [{comp.get('url')}]({comp.get('url')}) | {comp.get('description')} | {comp.get('strengths')} | {comp.get('weaknesses')} |\n"
            
        local_report += f"""
---

## 📈 Market Sizing (TAM/SAM/SOM)
* **Total Addressable Market (TAM)**: {market_analysis.get('tam', 'Not estimated')}
* **Serviceable Addressable Market (SAM)**: {market_analysis.get('sam', 'Not estimated')}
* **Serviceable Obtainable Market (SOM)**: {market_analysis.get('som', 'Not estimated')}

### Calculation Logic:
{market_analysis.get('sizing_breakdown', 'No logic supplied.')}

---

## ⚡ SWOT and Risk Mitigations

### SWOT Matrix
* **Strengths**: {', '.join(risks.get('swot', {}).get('strengths', []))}
* **Weaknesses**: {', '.join(risks.get('swot', {}).get('weaknesses', []))}
* **Opportunities**: {', '.join(risks.get('swot', {}).get('opportunities', []))}
* **Threats**: {', '.join(risks.get('swot', {}).get('threats', []))}

### Critical Risk Factors:
| Risk Category | Description | Probability | Impact | Mitigation |
| :--- | :--- | :---: | :---: | :--- |
"""
        for risk in risks.get("matrix", []):
            local_report += f"| {risk.get('risk_category')} | {risk.get('description')} | {risk.get('probability')} | {risk.get('impact')} | {risk.get('mitigation')} |\n"
            
        local_report += f"""
---

## 🛠️ Technical Implementation Blueprint
* **Frontend Framework**: {tech_stack.get('frontend', 'Not specified')}
* **Backend middleware**: {tech_stack.get('backend', 'Not specified')}
* **Core Database**: {tech_stack.get('database', 'Not specified')}
* **Hosting Platforms**: {tech_stack.get('infrastructure_hosting', 'Not specified')}
* **Monthly infrastructure budget**: {tech_stack.get('cost_estimate', 'Not specified')}

### Recommended MVP Features (Must-Have):
"""
        for feature in tech_stack.get("mvp_features", []):
            local_report += f"- {feature}\n"
            
        local_report += f"\n*CTO Justification*: {tech_stack.get('justification', 'No technical notes.')}\n"
        
        return {
            "report": local_report,
            "current_agent": "report_generator",
            "logs": logs + [f"Report Generator Agent: Compiled validation report locally (parametric fallback: {e})."]
        }
